### ISSUE TITLE
Using -u propagates --gpu-loops which results in an 'invalid argument specified'

### ISSUE THREAD

**Issue by nucleare** [philsmd/analyze_hc_restore#4]
![goodbye-gpu-loops](https://user-images.githubusercontent.com/29671486/133511771-30484dd8-9775-42ce-8c2c-b83696359844.png)

As discovered while using Hashcat v 5.10 on Ubuntu Desktop 20.04.3 LTS, addressed in pull request #3 while enabling the necessary accompaniment of --force option to allow usage.

Please feel free to adjust accordingly as I plead being excused for any lack of formalities.

**Comment by philsmd** [comment]
indeed a valid issue, I've commented now in #3 what I recommend changing before merging your changes. thank you

**Comment by philsmd** [comment]
fixed with commit https://github.com/philsmd/analyze_hc_restore/commit/169a315

thanks for the report and fix !

**Comment by nucleare** [comment]
Thank you for merging! And Thank YOU for sharing such a useful tool with the community!
